package com.hisptz.hris.Bundles.DashboardChartBundle;

/**
 * Created by Guest on 8/16/18.
 */
import com.hisptz.hris.core.Model.Model;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.util.Date;
import java.util.Objects;

// TODO: Change the uid property to autogenerated for all entities
// TODO: Wire relationships between entities for the whole database


@Entity
@EntityListeners(AuditingEntityListener.class)
@Table(name = "dashboardchart")
public class DashboardChart extends Model {
    private Integer fieldoneId;
    private Integer fieldtwoId;
    private Integer userId;
    
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String uid;
    
    private String name;
    private String description;
    private String graphtype;
    private Boolean lowerlevels;
    private Boolean systemwide;
    
    @Temporal(TemporalType.TIMESTAMP)
    @CreatedDate
    private Date datecreated;
    
    @Temporal(TemporalType.TIMESTAMP)
    @LastModifiedDate
    private Date lastupdated;


    public DashboardChart() {
    }


    public DashboardChart(Long id) {
        this.id = id;
    }

    public DashboardChart(Integer fieldoneId, Integer fieldtwoId, Integer userId, String name, String description, String graphtype, Boolean lowerlevels, Boolean systemwide) {
        this.fieldoneId = fieldoneId;
        this.fieldtwoId = fieldtwoId;
        this.userId = userId;
        this.name = name;
        this.description = description;
        this.graphtype = graphtype;
        this.lowerlevels = lowerlevels;
        this.systemwide = systemwide;
    }

    public Boolean getLowerlevels() {
        return lowerlevels;
    }

    public Boolean getSystemwide() {
        return systemwide;
    }


    @Basic
    @Column(name = "fieldone_id")
    public Integer getFieldoneId() {
        return fieldoneId;
    }

    public void setFieldoneId(Integer fieldoneId) {
        this.fieldoneId = fieldoneId;
    }

    @Basic
    @Column(name = "fieldtwo_id")
    public Integer getFieldtwoId() {
        return fieldtwoId;
    }

    public void setFieldtwoId(Integer fieldtwoId) {
        this.fieldtwoId = fieldtwoId;
    }

    @Basic
    @Column(name = "user_id")
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Basic
    @Column(name = "uid")
    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    @Basic
    @Column(name = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Basic
    @Column(name = "description")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Basic
    @Column(name = "graphtype")
    public String getGraphtype() {
        return graphtype;
    }

    public void setGraphtype(String graphtype) {
        this.graphtype = graphtype;
    }

    @Basic
    @Column(name = "lowerlevels")
    public Boolean isLowerlevels() {
        return lowerlevels;
    }

    public void setLowerlevels(Boolean lowerlevels) {
        this.lowerlevels = lowerlevels;
    }

    @Basic
    @Column(name = "systemwide")
    public Boolean isSystemwide() {
        return systemwide;
    }

    public void setSystemwide(Boolean systemwide) {
        this.systemwide = systemwide;
    }

    @Basic
    @Column(name = "datecreated")
    public Date getDatecreated() {
        return datecreated;
    }

    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }

    @Basic
    @Column(name = "lastupdated")
    public Date getLastupdated() {
        return lastupdated;
    }

    public void setLastupdated(Date lastupdated) {
        this.lastupdated = lastupdated;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DashboardChart that = (DashboardChart) o;
        return id == that.id &&
                lowerlevels == that.lowerlevels &&
                systemwide == that.systemwide &&
                Objects.equals(fieldoneId, that.fieldoneId) &&
                Objects.equals(fieldtwoId, that.fieldtwoId) &&
                Objects.equals(userId, that.userId) &&
                Objects.equals(uid, that.uid) &&
                Objects.equals(name, that.name) &&
                Objects.equals(description, that.description) &&
                Objects.equals(graphtype, that.graphtype) &&
                Objects.equals(datecreated, that.datecreated) &&
                Objects.equals(lastupdated, that.lastupdated);
    }

    @Override
    public int hashCode() {

        return Objects.hash(id, fieldoneId, fieldtwoId, userId, uid, name, description, graphtype, lowerlevels, systemwide, datecreated, lastupdated);
    }
}